### ISSUE TITLE
Create Github Actions for sz-sdk-go-core

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/sz-sdk-go-core#150]
Create GitHub actions that do: 

- [ ] **Code coverage:** `go tool cover`
- [ ] **Code format checking:** `gofmt`
- [ ] **Security checking:** `gosec`
- [ ] **Static analysis:** `go vet`
- [ ] **Syntax checking:** `gofmt`
- [ ] **Unit testing:** `go test`

### References

- https://github.com/senzing-garage/garage-roadmap/issues/8
- https://github.com/senzing-garage/g2-sdk-go/issues/125

**Comment by kernelsam** [comment]
Implemented as part of: https://github.com/senzing-garage/sz-sdk-go-core/commit/271bed7924b2978e4230e0da1a3e5d9859924cb4
